variable "bucket_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "cloudfront_domain_name" {}
variable "db_host" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
